### ISSUE TITLE
Installation problems with galahad 2.3 

### ISSUE THREAD

**Issue by FabioRigamonti** [dynamics-of-stellar-systems/dynamite#161]
After following the instructions for the installation of galahad 2.3 and dynamite 1.0.0 the installation process breaks after running the command: "make all" giving the following errors attached in the 2 screenshots:

![installation_error_2](https://user-images.githubusercontent.com/65313023/125478016-d63becd3-430d-45a7-a955-59da75fc5712.png)
![installation_error_1](https://user-images.githubusercontent.com/65313023/125478024-52119c94-c143-475f-8f4d-062b4e55e32c.png)

The screenshots refer to a system with Linux Manjaro Xfce 64 bit using  gfortran version 9.0
The same errors can be reproduced also on Linux CentOS 7 and Ubuntu 20.04.2.

We "solved" this problem by installing the latest version of galahad and changing a couple of lines in the makefile.

We changed GALAHADDIR in order to point to the new galahad directory.
We added the following flags:

 -lgalahad_spral -lgalahad_pardiso -lgalahad_wsmp -lgalahad_mkl_pardiso

in the triaxnnls_CRcut and triaxnnls_noCRcut compilation lines.

 
p.s. It seems that gfortran has the static libraries only in the ubuntu version, in the other cases it has been necessary to change line 84 of the makefile removing the "-static-libgfortran".

**Comment by ejlilley** [comment]
This should be fixed according to `Makefile.linux` and `README.linux` (this will be clarified in the documentation).
