### ISSUE TITLE
Make sure the documentation can be compiled with the latest version of Sphinx

### ISSUE THREAD

**Issue by maindlt** [dynamics-of-stellar-systems/dynamite#233]

**Comment by azocchi** [comment]
The error I was getting was the following: 
```Could not import extension IPython.sphinxext.ipython_console_highlighting (exception: No module named 'IPython.sphinxext')```

I finally managed to fix this and to compile the documentation on Fedora 36 after installing ```python3-ipython-sphinx```. Make sure that ```ipython``` is up to date, and with this extra package it should work!
