### ISSUE TITLE
Create globals.py

### ISSUE THREAD

**Issue by maindlt** [dynamics-of-stellar-systems/dynamite#249]
Have a file globals.py that defines global constants like G, parsec_to_km, etc.

**Comment by ejlilley** [comment]
Things that look like they should be global constants (from plotter.py):

-         grav_const_km = 6.67428e-11*1.98892e30/1e9
-         parsec_km = 1.4959787068e8*(648.000e3/np.pi)
-         rho_crit = (3.*((7.3000e-5)/parsec_km)**2)/(8.*np.pi*grav_const_km)
