### ISSUE TITLE
Typo in plotter.py

### ISSUE THREAD

**Issue by momomaycry** [dynamics-of-stellar-systems/dynamite#264]
https://github.com/dynamics-of-stellar-systems/dynamite/blob/7d495531cb6d22b9380edc3a916ccf9a6594d4a3/dynamite/plotter.py#L975

should be 
`Qjth = (1 - sth**2) * (1 - sphi**2) + \`

This was a typo existed in the IDL code, and Ling founded it recently.

**Comment by Jehan-h20220012** [comment]
Please assign me this issue.
I will raise pull request to solve it.

**Comment by Jehan-h20220012** [comment]
Please merge my Pull Request

**Comment by gsantucci90** [comment]
I thought this has already been fixed a year ago? Isn't it the same issue as here: https://github.com/dynamics-of-stellar-systems/dynamite/issues/77

**Comment by Jehan-h20220012** [comment]
No sir, I have made the necessary changes and made a pull request.
Please merge it.

**Comment by Jehan-h20220012** [comment]
Please merge my Pull Request

**Comment by Jehan-h20220012** [comment]
> I thought this has already been fixed a year ago? Isn't it the same issue as here: #77

The issue was never closed even though it was raised a year ago. In the latest code I could find the issue still persisiting.
