### ISSUE TITLE
Improve handling of models not created by the model iterator

### ISSUE THREAD

**Issue by maindlt** [dynamics-of-stellar-systems/dynamite#287]
Apart from using the model iterator, a model can be instantiated directly with a certain parameter set, e.g. by directly calling `model=dyn.model.Model(config=c, parset=parset)`.

The current implementation of this has the following issues which came up when investigating @juliala254's comments in issue #284 (specifically, no. 6). Many thanks, @juliala254!

- If there is no `all_models.ecsv` table, then a standard model directory `orblib_000_000/ml<ml-value of model parset>` will be assigned and subsequently calling `model.get_orblib()` and `model.get_weights()` will calculate the model as illustrated in tutorial `2_quickstart.ipynb`. This works, but some issues arise here:
  - Subsequently changing the parameter set (like suggested in the mentioned tutorial) and re-instantiating the model will lead to the same standard model directory. Hence, `model.get_orblib()` will think the orbit library has already been created and without explicitly deleting the model directory before integrating the orblib DYNAMITE will silently always use the same orblib no matter what underlying parameters have changed.
  - Deleting the standard model directory is a quick fix for this behavior, but the issues of (a) no record of the actually used parset and (b) losing the calculation results of the ‘manually’ created models remain.
  - There is no record of the actual parameter set of this model because there is no `all_models.ecsv` file and none is created.

- If there is an existing all_models table, then trying to directly instantiating a new model via `model=dyn.model.Model(config=c, parset=parset)` will raise an exception if the parset is not existing in the all_models table already.

To my mind a solution to this should make sure that (i) explicitly generated models do not interfere with possibly existing models in the all_models table, (ii) it is possible to run explicit models if an all_models table is existing, and (iii) parset values of those models are recorded.

Ideas:
- Add the explicitly generated models into the all_models table but use a different directory naming scheme (e.g. `orblib_explicit_<index>` instead of `orblib_xxx_yyy`) or to keep them in a separate table like `manual_models.ecsv`. The first alternative would probably be preferable because it makes all models available to possible future iteration runs…
- Quite pragmatic: discourage the use of 'manually' instantiated models and make the model iterator the only supported way of running models.

Looking forward to any comments and cheers,
Thomas

**Comment by azocchi** [comment]
Just a small comment to this: I just tested the code in PR #263, and it is indeed possible to generate one single model with that setup, just by specifying one single value following the `fixed_values` keyword in the config file. I think that indeed we can use the Tutorial 2 to explain how the SpecificModels parameter generator works! :) Thanks for setting this up, @maindlt!

**Comment by maindlt** [comment]
> I think that indeed we can use the Tutorial 2 to explain how the SpecificModels parameter generator works! :)

Great idea @azocchi - as soon as we have merged PR #263 I can update tutorial 2 to use the new parameter generator :-)

**Comment by maindlt** [comment]
Closed due to merging of PR #263.
