### ISSUE TITLE
Urgent: pyfort_GaussHerm error when importing dyna

### ISSUE THREAD

**Issue by sthater** [dynamics-of-stellar-systems/dynamite#292]
Jesse's student had some issues with the dynamite python install. He’s getting a weird error when trying to import the dynamite code.

>>> import dynamite as dyn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/suphys/mlan9395/dynamite-master/dynamite/__init__.py", line 1, in <module>
    from dynamite import constants, data, mges, orbit_exploration, orblib, physical_system, populations, weight_solvers, parameter_space, model, config_reader, model_iterator, kinematics, plotter, myrand
  File "/suphys/mlan9395/dynamite-master/dynamite/orbit_exploration.py", line 10, in <module>
    from dynamite import pyfort_GaussHerm
ImportError: cannot import name 'pyfort_GaussHerm' from partially initialized module 'dynamite' (most likely due to a circular import) (/suphys/mlan9395/dynamite-master/dynamite/__init__.py)
>>> 

I also noticed this last week with Julia when we tried to install dyna for her on the cluster. Have you also seen this? 

The package is responsible for the orbital decomposition and reprojection. For Julia it had helped to just comment the line out. Is it still needed?

Best wishes,

Sabine

**Comment by maindlt** [comment]
Closed due to merging PR #281
