### ISSUE TITLE
Installation error (related to miniconda environment?)

### ISSUE THREAD

**Issue by maindlt** [dynamics-of-stellar-systems/dynamite#296]
Running tests, errors occur, e.g.

`[ERROR] 14:38:34 - dynamite.orblib.LegacyOrbitLibrary - cmd_orb_start exit code 127. ERROR. Message: cmd_orb_start: line 2: /opt/miniconda3/envs/dcdirect/lib/python3.10/site-packages/legacy_fortran/orbitstart: No such file or directory`

The copy of the `legacy_fortran` directory doesn't even exist:

```
(dcdirect) prash@air > ls /opt/miniconda3/envs/dcdirect/lib/python3.10/site-packages/legacy_fortran
ls: /opt/miniconda3/envs/dcdirect/lib/python3.10/site-packages/legacy_fortran: No such file or directory
```

but the executables are all made correctly in `dynamite/legacy_fortran`.

This should have been solved with an earlier commit (1ae1c67) and hence may be related to miniconda environments?
Check and solve...

**Comment by prashjet** [comment]
Solution: remove all dynamite eggs from the `site_packages`
