### ISSUE TITLE
Chi2 map wrong axis label

### ISSUE THREAD

**Issue by juliala2504** [dynamics-of-stellar-systems/dynamite#312]
The Chi2 map plot has wrong axis label, it shows "M-BH" for y label instead of "log(M_BH/M_sun)".

I wanted to change it and first tried "log(M_BH/M_\odot)" since it is a LaTeX description and in latex \odot works but dynamite doesn't take it and gives me error messages back. 

Additionally, if you let two parameters vary the colorbar for the chi2 value is directly on the x axis thus the ticks of the axis and the colorbar overlap.

**Comment by maindlt** [comment]
Hi @juliala2504,

PR #365 should fix this, do you have time to test that PR?

Many thanks and cheers,
Thomas
