### ISSUE TITLE
model.get_weights() gives an error when run

### ISSUE THREAD

**Issue by TomasHRutherford** [dynamics-of-stellar-systems/dynamite#323]
When running the tutorial notebook 2 or any model, the command "model.get_weights()" gives an error when run:

ValueError: Directory path_here/output/209185/models/orblib_000_000/ml02.00/ not in all_models table. all_models table: m-bh a-bh f-dh q-stars p-stars ... weights_done all_done which_iter directory
---- ---- ---- ------- ------- ... ------------ -------- ---------- ---------

It seems to be related to the code not creating the "all_models.ecsv" file properly when doing an initial run.

**Comment by maindlt** [comment]
Many thanks for pointing this out! Unfortunately, the tutorials are not 100% current in the sense that we encourage creating models exclusively via the `ModelIterator` class, which is a method that ensures all new models are added to the `all_models.ecsv` table correctly, much like demonstrated in the `dev_tests/test_nnls.py` test script. We expect to release a new set of tutorials in the weeks to come to reflect this.

As a preview of the new tutorial notebook 2, please have a look at the tutorial `2_quickstart.ipynb` in branch `tutorial_doc_fixes`, but please note: that branch is a development branch and needs to be treated strictly experimental.

**Comment by maindlt** [comment]
Closing this issue for now because the fix has been merged into the master branch and will be part of the next release.
