### ISSUE TITLE
Getting error in running the make all command in the legacy_fortran ?

### ISSUE THREAD

**Issue by avichaturvedi** [dynamics-of-stellar-systems/dynamite#324]
Dear dynamite support,

I am trying to install DYNAMITE on my cluster network. After installing the Galahad-2.3 and changing the path in the bashrc file, when I am trying to run 'make all' command in legacy-fortran folder, I am getting following error. 

<img width="1284" alt="Screenshot 2023-09-18 at 14 39 31" src="https://github.com/dynamics-of-stellar-systems/dynamite/assets/125473899/d5f0a927-1186-4fd4-b7d6-c4a6715c676d">

I dont understand the error. Many thanks for checking into this. 
Thank you.

Regards
Avinash

Here is my  gfortran version and cluster info : 

<img width="567" alt="Screenshot 2023-09-18 at 14 34 56" src="https://github.com/dynamics-of-stellar-systems/dynamite/assets/125473899/556ff586-74ab-4ffb-9a81-74017c2e25db">

<img width="1387" alt="Screenshot 2023-09-18 at 14 34 28" src="https://github.com/dynamics-of-stellar-systems/dynamite/assets/125473899/1daf73e0-d4f0-4e9d-89ae-8262a24034d2">

**Comment by maindlt** [comment]
Dear Avinash,

this error is covered in the documentation:
Please go to the online installation guide at https://dynamics.univie.ac.at/dynamite_docs/getting_started/installation.html, scroll all the way down to the section `Compile errors when building legacy Fortran code`, and follow the instructions there.

I'll close this issue for now, please re-open in case the solution in the docs does not work for you.

All the best,
Thomas

**Comment by avichaturvedi** [comment]
Dear Thomas, 

Thanks for the help. I followed the instructions and managed to execute the ''make all', command. However, I am not getting all the executables files for example : modelgen, partgen and triaxnnls_CRcut. I get the following error on running make all command. 

I hope you can see the error. 

<img width="1609" alt="Screenshot 2023-09-18 at 22 10 35" src="https://github.com/dynamics-of-stellar-systems/dynamite/assets/125473899/49162d1d-8079-408e-b774-7cbc373fa405">

Thanks for the support. 

Regards
Avinash

**Comment by maindlt** [comment]
Hm, looks like there's a problem with GALAHAD. Did it install correctly?
