### ISSUE TITLE
change `plotbin` requirement to `==3.1.3`

### ISSUE THREAD

**Issue by prashjet** [dynamics-of-stellar-systems/dynamite#327]
Currently the requirement is `plotbin>=3.1.3`. My latest `dynamite` install attempt installed plotbin version 3.1.5. This led to the following error when running `test_nnls`:

`ModuleNotFoundError: No module named 'plotbin.display_pixels'`

This error disappears when using plotbin version 3.1.3. I suggest fixing our plotbin requirement to 3.1.3.

Alternatively, we update our code to be compatible with 3.1.5.

**Comment by maindlt** [comment]
Hm, strange, on my machine it seems to work:

```
Python 3.9.13 (main, Aug 25 2022, 18:29:29)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import plotbin.display_pixels
>>> plotbin.__version__
'3.1.5'
>>>
```

But if your problem persists, I'd vote for fixing the version to 3.1.3...
