### ISSUE TITLE
Error in running example tutorial 'model.get_orblib()'

### ISSUE THREAD

**Issue by avichaturvedi** [dynamics-of-stellar-systems/dynamite#328]
Dear Dynamite team, 

I installed the latest version of the Dynamite (v4.0) and am trying to run the example tutorials of galaxy NGC6278. I am getting error in running the command "model.get_orblib()". To make sure that I have installed everthing properly, I run the 'python test_orbit_losvds.py' and am getting the same error. Following is the output from the terminal. Could you please help me, is it something to do with the installation or config file ? 

<img width="1107" alt="Screenshot 2023-10-05 at 10 24 41" src="https://github.com/dynamics-of-stellar-systems/dynamite/assets/125473899/a77e8602-9201-485e-9f06-b025a29005a5">

Thanks for the help. 

Regards
Avinash

**Comment by maindlt** [comment]
Dear Avinash,

it's most probably neither your config file nor your installation, this is unfortunately a bug (actually, two). Here are the fixes (currently in draft):

- The tutorials are currently changed to run with the latest code version (see comment in Issue #323 and preliminary new tutorial versions in branch `tutorial_doc_fixes`)
- Pull request #320 fixes test_orbit_losvds.py

Please note that these fixes are currently somewhat in beta and will be merged into the master branch, probably involving a new minor release, when finalized...

Best regards,
Thomas

**Comment by maindlt** [comment]
Hi Avinash,

I am closing this issue for now because the fixes were merged into the master branch and will be part of the next release.

Best regards,
Thomas
