### ISSUE TITLE
Compilation issues about GCC version

### ISSUE THREAD

**Issue by KerrrIce** [dynamics-of-stellar-systems/dynamite#335]
When I tried to compile the code on the cluster with default gcc 7.5.0, such a error was reported:
![compilation_error](https://github.com/dynamics-of-stellar-systems/dynamite/assets/82423277/f1a5d379-16f3-44e3-b6f7-aa6b1eade5d3)

Another error was reported when i used gcc 10.1.0:
![compilation_error_10](https://github.com/dynamics-of-stellar-systems/dynamite/assets/82423277/84da9a98-0850-4456-baa0-03f41865a0b0)

Is it due to the gcc version? If so, is there a recommended version of gcc?
Thank you!

**Comment by maindlt** [comment]
Hello @KerrrIce,

any halfway current version of gcc should work. Recently I tested successfully with gfortran/gcc 8.5.0 and 12.2.0.

About your first question: based on the the error message I suspect that galahad was built with a different gfortran version than the one you use for compiling DYNAMITE. I recommend you try compiling them with the same gfortran version.

About the second question: please refer to the installation documentation ("Compile errors when building legacy Fortran code" at the bottom of the page https://dynamics.univie.ac.at/dynamite_docs/getting_started/installation.html). In short, it suggests to try the following:
- In `legacy_fortran/Makefile`, identify the line `flags +=    -funroll-loops -ftree-loop-linear`
- Change that line to `flags +=    -funroll-loops # -ftree-loop-linear`

Hope that helps!

All the best,
Thomas
