### ISSUE TITLE
Dyna install issue

### ISSUE THREAD

**Issue by sthater** [dynamics-of-stellar-systems/dynamite#345]
A copy of a mail by Nilanjana:

I am facing an issue while installing the DYNAMITE software which I can't solve using the GitHub issue page. 
For the installation, I have followed this [link](https://dynamics.univie.ac.at/dynamite_docs/getting_started/installation.html). The issue arises while compiling the fortran programs.
At the "make all" step, I get the following error :
collect2: error: ld returned 1 exit status
make: *** [Makefile:278: triaxnnls_CRcut] Error 1
[For your reference, my output matches the screenshots shown in this issue page - [link](https://github.com/dynamics-of-stellar-systems/dynamite/issues/342).]

As mentioned in this [link](https://github.com/dynamics-of-stellar-systems/dynamite/issues/335), I have tried changing the command from flags += -funroll-loops -ftree-loop-linear to  flags += -funroll-loops # -ftree-loop-linear but got the same error.
After doing 'make all', I am not get all the executables as mentioned in the installation guide which is possibly due to some error while installing GALAHAD ([link](https://github.com/dynamics-of-stellar-systems/dynamite/issues/324)). As suggested [here](https://github.com/dynamics-of-stellar-systems/dynamite/issues/161), I have tried to install GALAHAD separately which comes with its own issues during the installation.
I also have tried the executables available at this [link](https://github.com/dynamics-of-stellar-systems/dynamite/issues/35).

**Comment by maindlt** [comment]
Hi @NilanjanaNandi,

yes, it seems something went wrong in installing GALAHAD. Does installing the Fortran executables without GALAHAD work? The command for this is `make distclean; make nogal`. This will result in DYNAMITE only working with the Python NNLS (and not LegacyWeightSolver) with minimal impact. Note about working with the tutorials: the weight_solver_settings in the tutorials' config files would need to be changed from
```
weight_solver_settings:
    type: "LegacyWeightSolver"
    nnls_solver: 1
```
to
```
weight_solver_settings:
    type: "NNLS"
    nnls_solver: 'scipy'
```

Best regards,
Thomas

**Comment by NilanjanaNandi** [comment]
I could possible install DYNAMITE. This is the output of _test-nnls.py_.
![kinchi2_vs_model_id](https://github.com/dynamics-of-stellar-systems/dynamite/assets/135123881/75abe9f2-9b2b-47f3-84b3-a9e622469dcb)

The chi^2 is much higher compared to the plot shown in the installation guide but the code is running fine.
![kinematic_map_kinset1](https://github.com/dynamics-of-stellar-systems/dynamite/assets/135123881/6b81224b-91a2-4969-89df-236a9e3764df)
Also, h_3 and h_4 moments are blank in the kinematic map. 
I wonder if these are arising (chi^2 plot : what I obtained vs the result shown [here](https://dynamics.univie.ac.at/dynamite_docs/getting_started/installation.html#test-run) and the absence of h_3 and h_4) as a result of using a different type of the weight solver. 

What is the difference between the (1) DYNAMITE with the GALAHAD (the LegacyWeightSolver) and the SciPy-based NNLS weight solvers (installation option A) and (2) DYNAMITE with just the SciPy-based NNLS weight solver (installation option B). 
Does it make huge difference in the output results?

Many thanks for solving my issue. 
Regards,
Nilanjana

**Comment by maindlt** [comment]
Hi Nilanjana,

your results from `test_nnls.py` look as expected and I think your installation is ok:
- The chi^2 plot is the right one, we missed exchanging the image in the documentation after switching from chi2 to kinchi2. There is a pull request (#347) in process that will fix this, along with other documentation improvements. Many thanks for pointing this out!
- The kinematic maps also look correct, the blank values in h_3 and h_4 are real (see the zero columns in the kinematics input `dev_tests/NGC6278_input/gauss_hermite_kins.ecsv`).
- In our tests with several galaxies the installation options A and B produce identical or very very close results. The difference is that installation option B does not install the GALAHAD-based weight solver, but only the SciPy and cvxopt-based Python solvers. The installation of GALAHAD caused problems with some users and we may probably drop GALAHAD support in the future (this is just a personal comment, it has not been officially decided though). One consequence of not having GALAHAD is that in the current release the beta plots (`Plotter.beta_plot(...)`) are not supported. This will be added in the next release and you already can use the beta plots with the Python weight solvers when you pull the current master branch.

Please let us know whether this works for you.

All the best,
Thomas

**Comment by NilanjanaNandi** [comment]
Perfect!
Many many thanks for your help.

**Comment by maindlt** [comment]
Wonderful, have a great day!
