### ISSUE TITLE
Python error in running new iteration of models

### ISSUE THREAD

**Issue by avichaturvedi** [dynamics-of-stellar-systems/dynamite#391]
Dear Dynamite team (@maindlt), 

I am running Dynamite models for one of the galaxy using its MUSE IFU observations. I managed to run initial models, however for new iterations, I am getting some python error, which stops the code from running new iterations. Following is the screenshot of the error.  

<img width="1240" alt="Screenshot 2024-05-28 at 16 22 13" src="https://github.com/dynamics-of-stellar-systems/dynamite/assets/125473899/4d2293bb-a2e4-4c09-bf8c-8c43f188327b">

Any suggestions to solve this problem will be very helpful. 

Thanks for your help and suggestions. 

Regards
Avinash

![kinmapchi2_plot](https://github.com/dynamics-of-stellar-systems/dynamite/assets/125473899/41807d9c-230b-4837-8e48-5f7f8bce0c2b)

![kinmapchi2_progress_plot](https://github.com/dynamics-of-stellar-systems/dynamite/assets/125473899/0d627d47-e127-404f-b4a6-cb29b2d2898c)

**Comment by avichaturvedi** [comment]
Dear Thomas, 

Many thanks for your response. I have responed to your email and sent you the files which you have asked. In the meantime, I will attempt what you have suggested. Many thanks. 

Regards
Avinash

**Comment by maindlt** [comment]
Dear Avinash, I'll close this issue due to inactivity. Please feel free to re-open in case the issue persists...

Cheers,
Thomas
