### ISSUE TITLE
schwpy `schw_mass.py` error

### ISSUE THREAD

**Issue by prashjet** [dynamics-of-stellar-systems/dynamite#77]
A message from Ling

> I found another typo in schw_mass.py
> Line 137
> I think it should be
> Qjth = (1 - sth ** 2) * (1 - sphi ** 2) + (1 - sth ** 2) * sphi ** 2 / p_pot ** 2 + sth ** 2 / q_pot ** 2
> 
> Not
> Qjth = (1 - sth ** 2) * (1 - sphi) ** 2 + (1 - sth ** 2) * sphi ** 2 / p_pot ** 2 + sth ** 2 / q_pot ** 2
> 
> Unfortunately, this is also in the IDL version
> tri_mgetmass.pro
> 
> It makes noticeable difference in the resulting enclose stellar mass profile.
> Could you please help to double check?   Thank you.

**Comment by maindlt** [comment]
> Ling asks if we can double check the typo - I guess you can do this while re-implementing method!

@ejlilley, would you have time to look into this next week so we can fix it before the workshop?

Many thanks and cheers,
Thomas
